# Generated by Django 4.2.1 on 2023-06-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_remove_contact_id_contact_feedback_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="feedback_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
