# Generated by Django 4.2.1 on 2023-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_contact_alter_product_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="id",
        ),
        migrations.AddField(
            model_name="contact",
            name="feedback_id",
            field=models.AutoField(default="", primary_key=True, serialize=False),
        ),
    ]
