# Generated by Django 4.2.1 on 2023-06-05 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_remove_contact_id_contact_feedback_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="contact",
        ),
    ]
