# Generated by Django 4.2.1 on 2023-06-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="content",
            new_name="subject",
        ),
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.TextField(default=""),
        ),
    ]
