# Generated by Django 4.2.1 on 2023-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_rename_content_contact_subject_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(),
        ),
    ]
